### ISSUE TITLE
NullPointerException when pasting a Schematic

### ISSUE THREAD

**Issue by thephatcrew** [TheBusyBiscuit/ExoticGarden#104]
spigot 1.15.1
xmx 6144
xms 4096
permissions to folder 777
mineos on freenas

[08:52:54] [Server thread/INFO]: [WorldBorder] [Fill] Saving the world to disk, just to be on the safe side. (free mem: 2239 MB)
--
[08:52:54] [Server thread/WARN]: [ExoticGarden] Task #1004819 for ExoticGarden vDEV - 25 (git b5fce971) generated an exception
java.lang.NullPointerException: null
at me.mrCookieSlime.ExoticGarden.Schematic.Schematic.pasteSchematic(Schematic.java:111) ~[?:?]
at me.mrCookieSlime.ExoticGarden.PlantsListener.lambda$onGenerate$3(PlantsListener.java:201) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[08:52:56] [Server thread/WARN]: [ExoticGarden] Task #1004834 for ExoticGarden vDEV - 25 (git b5fce971) generated an exception
java.lang.NullPointerException: null
at me.mrCookieSlime.ExoticGarden.Schematic.Schematic.pasteSchematic(Schematic.java:111) ~[?:?]
at me.mrCookieSlime.ExoticGarden.PlantsListener.lambda$onGenerate$3(PlantsListener.java:201) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[08:52:57] [Server thread/WARN]: [ExoticGarden] Task #1004847 for ExoticGarden vDEV - 25 (git b5fce971) generated an exception
java.lang.NullPointerException: null
at me.mrCookieSlime.ExoticGarden.Schematic.Schematic.pasteSchematic(Schematic.java:111) ~[?:?]
at me.mrCookieSlime.ExoticGarden.PlantsListener.lambda$onGenerate$3(PlantsListener.java:201) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[08:52:58] [Server thread/INFO]: org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory@5c699645
[08:52:58] [Server thread/INFO]: org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory@102e9366
[08:52:59] [Server thread/INFO]: [WorldBorder] [Fill] 51 more chunks processed (494883 total, ~30.3%) (free mem: 3001 MB)
[08:53:03] [Server thread/WARN]: [ExoticGarden] Task #1004898 for ExoticGarden vDEV - 25 (git b5fce971) generated an exception
java.lang.NullPointerException: null
at me.mrCookieSlime.ExoticGarden.Schematic.Schematic.pasteSchematic(Schematic.java:111) ~[?:?]
at me.mrCookieSlime.ExoticGarden.PlantsListener.lambda$onGenerate$3(PlantsListener.java:201) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[08:53:04] [Server thread/INFO]: [WorldBorder] [Fill] 50 more chunks processed (494933 total, ~30.3%) (free mem: 1902 MB)

**Comment by AeSix** [comment]
getting similar
```
[17:28:09] [Server thread/INFO]: [ExoticGarden] Enabling ExoticGarden vDEV - 25 (git b5fce971)
[17:28:09] [Server thread/WARN]: [ExoticGarden] "ExoticGarden vDEV - 25 (git b5fce971)" has registered a listener for me.mrCookieSlime.CSCoreLibPlugin.events.ItemUseEvent on method "public void me.mrCookieSlime.ExoticGarden.FoodListener.onUse(me.mrCookieSlime.CSCoreLibPlugin.events.ItemUseEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [mrCookieSlime, Goldentoenail, Joapple, SoSeDiK]
```

**Comment by threlief** [comment]
was this issue resolved?? if so how do i fix it please and thank you

**Comment by AeSix** [comment]
@threlief 
I used CS-CoreLib 79,  SlimeFun4-366 and ExoticGarden build 22, and was able to generate a world, without errors, with trees, bushes, fruit, etc.  This arrangement is not compatible with some other add-ons however. 

*I* am doing somthing much more niche - using 3 other world-gen time plugins to create a much more custom world, and so when I had issue, I had to remove those in order to ensure they weren't causing issues with SF/EG.  They weren't.  I *think* if I pre-generate the world with SF4-366 and EG-22, I can then update those to newer versions and add the other add-ons.  I havn't had the time quite yet to see that happen though.   I have however done a LOT of testing with various versions, and if I udpate any one of the three plugins, the system breaks and I don't get a world generated with EG stuffs. 

I believe the issue is that the add-ons all need to be recompiled to use CS-CoreLib 80 and (more importantly) SlimeFun4-408, with 1.15.1 as the target server version.   I currently don't posses the ability to do this.  I also don't know how factually accurate that is, just an assumption. 

I hope this helps you!  :)

**Comment by roracle** [comment]
This issue is still a problem.

[13:50:29 WARN] : [ExoticGarden] Could not paste Schematic for Tree: LEMON_TREE (FileNotFoundExcption)

The files _are_ there, I checked.

**Comment by mrcoffee1026** [comment]
Since you're calling anything having to do with a schematic a duplicate, it's still doing this in build 31, but the error is reworded: 
[21:30:44 WARN]: [ExoticGarden] Could not paste Schematic for Tree: PEAR_TREE (ZipException)

Which results in all exotic garden trees growing as oak trees instead.
