### ISSUE TITLE
Unable to load plug-in 

### ISSUE THREAD

**Issue by TalentsRC** [TheBusyBiscuit/ExoticGarden#214]
I use it on the server（purpur1.16.5） but can't load it 

↓This is the log ↓
[17:03:42] [Server thread/ERROR]: Could not load 'plugins\[ճҺ-��չ]ExoticGarden-76.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: io/github/thebusybiscuit/slimefun4/libraries/dough/items/CustomItemStack
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:279) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: io/github/thebusybiscuit/slimefun4/libraries/dough/items/CustomItemStack
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 7 more
Caused by: java.lang.ClassNotFoundException: io.github.thebusybiscuit.slimefun4.libraries.dough.items.CustomItemStack
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 7 more
## Environment (Required)

<!-- You can also just run "/sf versions" and show us a screenshot of that. #186 

 - Minecraft Version:Purpur1.16.5-1171
 - CS-CoreLib Version:92
 - Slimefun Version:V4.9
 - ExoticGarden Version:76

**Comment by Flymetothemoon25** [comment]
got this too although only loading server for the first time with plugins and lots of other plugins- probably to-do with the new update

**Comment by TalentsRC** [comment]
> got this too although only loading server for the first time with plugins and lots of other plugins- probably to-do with the new update

Excuse me, have you solved it?

**Comment by WalshyDev** [comment]
Update to [Slimefun 966](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/Slimefun4-966.jar)
