### ISSUE TITLE
Could not pass event ChunkPopulateEvent to ExoticGarden vDEV - 77

### ISSUE THREAD

**Issue by L4BORG** [TheBusyBiscuit/ExoticGarden#225]
## Description (Required)

Not sure.

## Steps to reproduce the Issue (Required)

Not sure.

## Expected behavior (Required)

Not sure.

## Server Log / Error Report

```
[19:36:53] [Server thread/ERROR]: Could not pass event ChunkPopulateEvent to ExoticGarden vDEV - 77 (git a2c4b6d3)
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.block.impl.CraftLeaves cannot be cast to class org.bukkit.block.data.Rotatable (org.bukkit.craftbukkit.v1_17_R1.block.impl.CraftLeaves and org.bukkit.block.data.Rotatable are in unnamed module of loader 'app')
	at io.github.thebusybiscuit.exoticgarden.schematics.Schematic.pasteSchematic(Schematic.java:153) ~[ExoticGarden.jar:?]
	at io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.pasteTree(PlantsListener.java:220) ~[ExoticGarden.jar:?]
	at io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.onGenerate(PlantsListener.java:134) ~[ExoticGarden.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor465.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-404]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-404]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-404]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-404]
	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:978) ~[app:?]
	at net.minecraft.server.level.ChunkHolder.lambda$updateFutures$22(ChunkHolder.java:873) ~[app:?]
	at net.minecraft.server.level.ChunkMap$CallbackExecutor.run(ChunkMap.java:182) ~[app:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1251) ~[app:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:680) ~[app:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:534) ~[app:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:873) ~[app:?]
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getType(CraftBlock.java:215) ~[patched_1.17.1.jar:git-Paper-404]
	at io.github.thebusybiscuit.exoticgarden.schematics.Schematic.pasteSchematic(Schematic.java:137) ~[ExoticGarden.jar:?]
	at io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.pasteTree(PlantsListener.java:220) ~[ExoticGarden.jar:?]
	at io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.onGenerate(PlantsListener.java:134) ~[ExoticGarden.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor465.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-404]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-404]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-404]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-404]
	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:978) ~[app:?]
	at net.minecraft.server.level.ChunkHolder.lambda$updateFutures$22(ChunkHolder.java:873) ~[app:?]
	at net.minecraft.server.level.ChunkMap$CallbackExecutor.run(ChunkMap.java:182) ~[app:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1251) ~[app:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:840) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1414) ~[patched_1.17.1.jar:git-Paper-404]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-404]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-404]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-404]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-404]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[19:36:53] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerEventException: Could not pass event ChunkPopulateEvent to ExoticGarden vDEV - 77 (git a2c4b6d3)
[19:36:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:647)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.Chunk.loadCallback(Chunk.java:978)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerChunk.lambda$updateFutures$22(PlayerChunk.java:873)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:182)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1251)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:680)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.world.level.World.getChunkAt(World.java:534)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.world.level.World.getType(World.java:873)
[19:36:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getType(CraftBlock.java:215)
[19:36:53] [Server thread/WARN]: 	at ExoticGarden.jar//io.github.thebusybiscuit.exoticgarden.schematics.Schematic.pasteSchematic(Schematic.java:137)
[19:36:53] [Server thread/WARN]: 	at ExoticGarden.jar//io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.pasteTree(PlantsListener.java:220)
[19:36:53] [Server thread/WARN]: 	at ExoticGarden.jar//io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.onGenerate(PlantsListener.java:134)
[19:36:53] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor465.execute(Unknown Source)
[19:36:53] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[19:36:53] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:36:53] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:36:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.Chunk.loadCallback(Chunk.java:978)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerChunk.lambda$updateFutures$22(PlayerChunk.java:873)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:182)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1251)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer.runTasks(ChunkProviderServer.java:840)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1414)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[19:36:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[19:36:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[19:36:53] [Server thread/WARN]: Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.block.impl.CraftLeaves cannot be cast to class org.bukkit.block.data.Rotatable (org.bukkit.craftbukkit.v1_17_R1.block.impl.CraftLeaves and org.bukkit.block.data.Rotatable are in unnamed module of loader 'app')
[19:36:53] [Server thread/WARN]: 	at ExoticGarden.jar//io.github.thebusybiscuit.exoticgarden.schematics.Schematic.pasteSchematic(Schematic.java:153)
[19:36:53] [Server thread/WARN]: 	at ExoticGarden.jar//io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.pasteTree(PlantsListener.java:220)
[19:36:53] [Server thread/WARN]: 	at ExoticGarden.jar//io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.onGenerate(PlantsListener.java:134)
[19:36:53] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor465.execute(Unknown Source)
[19:36:53] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[19:36:53] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:36:53] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:36:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[19:36:53] [Server thread/WARN]: 	... 29 more
```

## Environment (Required)

Paper git-Paper-404 (MC: 1.17.1)
Slimefun DEV - 990 (git 35e25eb8)
Metrics-Module #28
Java 16

Installed Addons: (3)
  EcoPower vDEV - 5 (git 5c1ecd68)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 77 (git a2c4b6d3)

**Comment by manul694** [comment]
+1
