### ISSUE TITLE
ExoticGarden vDEV - 2 fails to load in MC 1.13.1

### ISSUE THREAD

**Issue by tanewell** [TheBusyBiscuit/ExoticGarden#35]
The Exotic Garden plugin fails to load under MC version 1.13.1

Minecraft version Spigot 1.13.1 (latest version)
java version "1.8.0_181"
CS-CoreLib-28
Slimefun4-58
ExoticGarden-2
Essentials-2.x-SNAPSHOT
EssentialsAntiBuild-2.x-SNAPSHOT
EssentialsProtect-2.x-SNAPSHOT
EssentialsSpawn-2.x-SNAPSHOT
worldedit-bukkit-7.0.0-SNAPSHOT-dist

[09:34:00 INFO]: [ExoticGarden] Enabling ExoticGarden vDEV - 2 (git 393fe10c)
[09:34:00 ERROR]: Error occurred while enabling ExoticGarden vDEV - 2 (git 393fe10c) (Is it up to date?)
java.lang.NullPointerException: null
        at me.mrCookieSlime.ExoticGarden.ExoticGarden.registerTree(ExoticGarden.java:704) ~[?:?]
        at me.mrCookieSlime.ExoticGarden.ExoticGarden.onEnable(ExoticGarden.java:106) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by TheBusyBiscuit** [comment]
The current version of ExoticGarden is for 1.12, not 1.13
