### ISSUE TITLE
crash on 1.13 startup with Dev2 build

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/ExoticGarden#37]
Versions:
CS-CoreLib-29.jar
ExoticGarden-2.jar
Slimefun4-58.jar
This server is running CraftBukkit version git-Spigot-f6a273b-cd6252a (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)[m

[17:57:51] [Server thread/INFO]: [ExoticGarden] Enabling ExoticGarden vDEV - 2 (git 393fe10c)
[17:57:51] [Server thread/ERROR]: Error occurred while enabling ExoticGarden vDEV - 2 (git 393fe10c) (Is it up to date?)
java.lang.NullPointerException: null
	at me.mrCookieSlime.ExoticGarden.ExoticGarden.registerTree(ExoticGarden.java:704) ~[ExoticGarden-2.jar:?]
	at me.mrCookieSlime.ExoticGarden.ExoticGarden.onEnable(ExoticGarden.java:106) ~[ExoticGarden-2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.1-R0.1-SNAPSHOT.jar:git-Spigot-f6a273b-cd6252a]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.1-R0.1-SNAPSHOT.jar:git-Spigot-f6a273b-cd6252a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.1-R0.1-SNAPSHOT.jar:git-Spigot-f6a273b-cd6252a]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) [spigot-1.13.1-R0.1-SNAPSHOT.jar:git-Spigot-f6a273b-cd6252a]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) [spigot-1.13.1-R0.1-SNAPSHOT.jar:git-Spigot-f6a273b-cd6252a]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.1-R0.1-SNAPSHOT.jar:git-Spigot-f6a273b-cd6252a]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.1-R0.1-SNAPSHOT.jar:git-Spigot-f6a273b-cd6252a]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.1-R0.1-SNAPSHOT.jar:git-Spigot-f6a273b-cd6252a]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.1-R0.1-SNAPSHOT.jar:git-Spigot-f6a273b-cd6252a]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.1-R0.1-SNAPSHOT.jar:git-Spigot-f6a273b-cd6252a]
	at java.lang.Thread.run(Unknown Source) [?:?]

or link: https://pastebin.com/UwMGTRsU

Tried clearing all data from data-storage folder as well as emptying Exotic Garden and Slimefun folders... issue remained

**Comment by DrakstaarMSD** [comment]
These versions will unfortunately not work with 1.13. 
There is are 1.13 compatible Slimefun and CoresLib jar files that someone made.  I don't have a link with atm. 
Exotic Garden won't work properly as it has not been updated to 1.13 yet. :(
There are tons of changes made with the 1.13 update to minecraft and many plugins were broken because of it.

**Comment by mrcoffee1026** [comment]
All of these came from their repo server, since the cs-core and slimefun builds should be working with 1.13 and there was a build of exoticgardens ... and this was the only addon on this server... i believed this might be the only one made to work with 1.13... repo address here; https://thebusybiscuit.github.io/builds/
Not sure what "chestterminal" is but since there hasn't been a build since last year I wouldn't expect that to be 1.13 ready.  Since there was one for exotic garden last month, I did.  Looking over the notes on the pull request that would have created this last build... it doesn't have anything to do with 1.13 so I probably should have looked into it deeper before trying.

**Comment by DrakstaarMSD** [comment]
Yeah I think the EG additions were for the kitchen stuff and edibles. Not 100 % sure though.
I'm not a coder unfortunately. 
Though I've been tinkering with trying to get EG to work in 1.13.
I managed to get plants to work with the help of another plugin..Trees however, are another issue entirely.

**Comment by mrcoffee1026** [comment]
This version maybe should work with 1.13 so might need a simple remedy as attempting the regular .1.6.4 addon version at least let it run without crashing on startup with error messages.  So it's likely the build they're up to now should also work.

**Comment by mrcoffee1026** [comment]
Although the 1.6.4 version loads on startup without errors in the console on 1.13, it doesn't actually function.  While you can /give yourself the new items that's the only way to acquire them, the saplings will all grow into oak trees instead of the appropriate plants they are supposed to, so pretty likely the repo version of this will need an update in order to function in 1.13.
