### ISSUE TITLE
1.13.2 Oak Apple Tree fails to grow

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/ExoticGarden#55]
versions:
CraftBukkit v1_13_R2
CS-CoreLib vDEV - 36
Slimefun vDEV - 73
ExoticGarden vDEV - 6

Pre-existing Oak Apple Trees that exist in the world from prior versions are all fine, but attempting to plant a fresh Oak Apple Tree will only produce an Oak Tree along with this console error upon growth:

```
[11:19:44] [Server thread/ERROR]: Could not pass event StructureGrowEvent to ExoticGarden vDEV - 6 (git a0bf80ed)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:180) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:511) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1237) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at me.mrCookieSlime.ExoticGarden.Schematic.Schematic.pasteSchematic(Schematic.java:112) ~[ExoticGarden-6.jar:?]
	at me.mrCookieSlime.ExoticGarden.PlantsListener.onGrow(PlantsListener.java:53) ~[ExoticGarden-6.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	... 17 more

```

**Comment by SoSeDiK** [comment]
It works for me. I'm pretty sure you are using the old EG build since NPE can't be thrown in that part of code right now.
Thanks anyway, I figured out that trees weren't able to grow in CAVE_AIR because of this issue report.

**Comment by mrcoffee1026** [comment]
This is dev version 6 which I believe is the latest.  I was attempting to grow above ground at y=64 so I'm not sure what would have prevented it from being grown here.

**Comment by SoSeDiK** [comment]
Oh, I see. Yes, I changed some code parts in my current setup. Can you try it with #54 ?

**Comment by mrcoffee1026** [comment]
Yeah will do.  I saw your changes included non-decaying leaf blocks for the bushes... AWESOME.  Seems to be slow going getting new builds on the repo server but I have another two plugins taking forever with patches right now too, so I'll have to wait for the upgrade anyway.  Thanks again!

**Comment by SoSeDiK** [comment]
@mrcoffee1026, new build is available now.
I would be happy to hear if the issue is solved :)

**Comment by mrcoffee1026** [comment]
Ok tried planting another and got a similar console error to go with a vanilla oak tree that grew in place of the oak apple tree I planted:

`[14:04:35] [Server thread/ERROR]: Could not pass event StructureGrowEvent to ExoticGarden vDEV - 7 (git 521654c0)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:180) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:511) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1237) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at me.mrCookieSlime.ExoticGarden.Schematic.Schematic.pasteSchematic(Schematic.java:112) ~[ExoticGarden-7.jar:?]
	at me.mrCookieSlime.ExoticGarden.PlantsListener.onGrow(PlantsListener.java:55) ~[ExoticGarden-7.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-3cb9dcb-8b1588e]
	... 17 more
`

**Comment by SoSeDiK** [comment]
It's more like the Schematic is broken, I don't get this error.
Can you try to regenarate them?

**Comment by mrcoffee1026** [comment]
yeh!  That was the problem.  Removed the folder after rebooting the apple grew just fine, thanks much!
